version: 2
updates:
  # Root dependencies
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      dependencies:
        patterns:
          - "*"
    open-pull-requests-limit: 10

  # Frontend dependencies
  - package-ecosystem: "npm"
    directory: "/frontend"
    schedule:
      interval: "weekly"
    groups:
      dependencies:
        patterns:
          - "*"
    open-pull-requests-limit: 10

  # API Node dependencies
  - package-ecosystem: "npm"
    directory: "/api"
    schedule:
      interval: "weekly"
    groups:
      dependencies:
        patterns:
          - "*"
    open-pull-requests-limit: 10

  # System Design Frontend dependencies
  - package-ecosystem: "npm"
    directory: "/system-design/frontend"
    schedule:
      interval: "weekly"
    groups:
      dependencies:
        patterns:
          - "*"
    open-pull-requests-limit: 10

  # API Python dependencies
  - package-ecosystem: "pip"
    directory: "/api"
    schedule:
      interval: "weekly"
    groups:
      dependencies:
        patterns:
          - "*"
    open-pull-requests-limit: 10

  # Script dependencies
  - package-ecosystem: "pip"
    directory: "/scripts"
    schedule:
      interval: "weekly"
    groups:
      dependencies:
        patterns:
          - "*"
    open-pull-requests-limit: 10

  # Docker
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      dependencies:
        patterns:
          - "*"
    open-pull-requests-limit: 10
